import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

test('migração, isolamento, cotas, cobrança e expiração em PostgreSQL', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create schema storage;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      create table public.patrimonio(id bigint generated always as identity primary key, user_id uuid references auth.users, nome text);
      create table public.documentos_casa(id bigint generated always as identity primary key, patrimonio_id bigint references public.patrimonio, caminho_arquivo text unique);
      create table storage.objects(id bigint generated always as identity primary key,bucket_id text,name text);
      alter table storage.objects enable row level security;
      create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      insert into storage.buckets(id,public) values('documentos',true);
      grant usage on schema public,auth,storage to authenticated,anon;
      grant all on public.patrimonio,public.documentos_casa,storage.objects to authenticated,anon;
      grant usage,select on all sequences in schema public,storage to authenticated,anon;
    `);
    await db.exec(fs.readFileSync(new URL('../supabase/migrations/202609160001_planos.sql', import.meta.url), 'utf8'));
    const user = '00000000-0000-4000-8000-000000000001';
    const other = '00000000-0000-4000-8000-000000000002';
    await db.query('insert into auth.users values($1),($2)', [user, other]);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [user]);
    await db.exec('set role authenticated');
    await db.exec("insert into patrimonio(nome) values('Primeiro')");
    await assert.rejects(db.exec("insert into patrimonio(nome) values('Segundo')"), /Limite de patrimônios/);
    for (let i=0;i<5;i++) await db.query('insert into documentos_casa(patrimonio_id,caminho_arquivo) values(1,$1)', ['doc'+i]);
    await assert.rejects(db.exec("insert into documentos_casa(patrimonio_id,caminho_arquivo) values(1,'doc6')"), /Limite de documentos/);
    await db.exec("insert into storage.objects(bucket_id,name) values('documentos','doc0')");
    await assert.rejects(db.exec("insert into storage.objects(bucket_id,name) values('documentos','sem-reserva')"), /row-level security/);
    await assert.rejects(db.exec("insert into billing_subscriptions(user_id,plan) values(auth.uid(),'pro')"), /permission denied/);
    await assert.rejects(db.query("select billing_claim_checkout($1,'pro')", [user]), /permission denied/);
    await db.exec('reset role');
    const claim = (await db.query("select billing_claim_checkout($1,'basico') as data", [user])).rows[0].data;
    const sub = claim.subscription.id;
    assert.equal(claim.created,true);
    assert.equal((await db.query("select billing_claim_checkout($1,'basico') as data", [user])).rows[0].data.created,false);
    await db.exec('set role authenticated');
    assert.equal((await db.query('select my_plan() as data')).rows[0].data.plan,'free');
    await db.exec('reset role');
    const record = { provider_payment_id:'pay1',subscription_id:sub,invoice_id:'inv1',status:'approved',period_start:new Date(Date.now()-3600000).toISOString(),period_end:new Date(Date.now()+86400000).toISOString(),provider_updated_at:new Date().toISOString() };
    await db.query('select billing_record_payment($1)', [record]);
    await db.query('select billing_record_payment($1)', [record]);
    assert.equal((await db.query('select count(*)::int as n from billing_payments')).rows[0].n,1);
    await db.exec('set role authenticated');
    assert.equal((await db.query('select my_plan() as data')).rows[0].data.plan,'basico');
    await db.exec("insert into patrimonio(nome) values('Segundo'),('Terceiro')");
    const second = (await db.query("select id from patrimonio where nome='Segundo'")).rows[0].id;
    for (let i=0;i<5;i++) await db.query('insert into documentos_casa(patrimonio_id,caminho_arquivo) values($1,$2)', [second,'second'+i]);
    await assert.rejects(db.query('insert into documentos_casa(patrimonio_id,caminho_arquivo) values($1,$2)', [second,'second6']), /Limite de documentos/);
    await assert.rejects(db.exec("insert into patrimonio(nome) values('Quarto')"), /Limite de patrimônios/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [other]);
    assert.equal((await db.query('select * from patrimonio')).rows.length,0);
    assert.equal((await db.query('select * from documentos_casa')).rows.length,0);
    assert.equal((await db.query('select * from storage.objects')).rows.length,0);
    await assert.rejects(db.exec("insert into documentos_casa(patrimonio_id,caminho_arquivo) values(1,'intruso')"), /Proprietário inválido/);
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [user]);
    await db.exec('reset role');
    await db.query("update billing_subscriptions set status='cancelled' where id=$1", [sub]);
    assert.equal((await db.query('select my_plan() as data')).rows[0].data.plan,'basico');
    const pro = (await db.query("select billing_claim_checkout($1,'pro') as data", [user])).rows[0].data.subscription.id;
    await db.query('select billing_record_payment($1)', [{ ...record,provider_payment_id:'pay2',subscription_id:pro }]);
    await db.exec('set role authenticated');
    await db.exec("insert into patrimonio(nome) select 'Pro '||n from generate_series(1,10) n");
    for (let i=0;i<10;i++) await db.query('insert into documentos_casa(patrimonio_id,caminho_arquivo) values(1,$1)', ['pro'+i]);
    assert.equal((await db.query('select my_plan() as data')).rows[0].data.plan,'pro');
    await db.exec('reset role');
    await db.query('select billing_record_payment($1)', [{ ...record,provider_payment_id:'pay2',subscription_id:pro,status:'refunded',provider_updated_at:new Date(Date.now()+1000).toISOString() }]);
    await db.query('select billing_record_payment($1)', [{ ...record,provider_payment_id:'pay2',subscription_id:pro }]);
    assert.equal((await db.query('select my_plan() as data')).rows[0].data.plan,'basico');
    await db.exec("update billing_payments set period_start=now()-interval '2 months',period_end=now()-interval '1 month'");
    await db.exec('set role authenticated');
    const expired = (await db.query('select my_plan() as data')).rows[0].data;
    assert.equal(expired.plan,'free'); assert.equal(expired.assets,13); assert.equal(expired.documents,20);
    await assert.rejects(db.exec("insert into patrimonio(nome) values('Acima do Free')"), /Limite de patrimônios/);
    await assert.rejects(db.query('update patrimonio set user_id=$1 where id=1',[other]), /transferir/);
    await db.exec("update patrimonio set nome='Pode editar' where id=1");
    await db.exec('delete from documentos_casa where id=(select min(id) from documentos_casa)');
    await db.exec('reset role; set role anon');
    assert.equal((await db.query('select * from patrimonio')).rows.length,0);
    await assert.rejects(db.query('select my_plan()'), /permission denied/);
  } finally { await db.close(); }
});
